include ../../Makefile.mk

build-centos7:
	docker compose up primary1-centos7 -d

build-centos8:
	docker compose up primary1-centos8 -d

build-rocky8:
	docker compose up primary1-rocky8 -d

build-rocky9:
	docker compose up primary1-rocky9 -d

build-rhel8:
	docker compose up primary1-rhel8 -d

build-almalinux8:
	docker compose up primary1-almalinux8 -d

build-debian9:
	docker compose up primary1-debian9 -d

build-debian10:
	docker compose up primary1-debian10 -d

build-debian11:
	docker compose up primary1-debian11 -d

build-ubuntu20:
	docker compose up primary1-ubuntu20 -d

build-ubuntu22:
	docker compose up primary1-ubuntu22 -d

build-suse15:
	docker compose up primary1-suse15 -d

build-oraclelinux7:
	docker compose up primary1-oraclelinux7 -d

build-oraclelinux8:
	docker compose up primary1-oraclelinux8 -d

build-oraclelinux9:
	docker compose up primary1-oraclelinux9 -d
