# syntax=docker/dockerfile:1

FROM jrei/systemd-debian:11

RUN apt update
RUN apt install sudo -y
RUN apt install python3 -y
RUN apt install ca-certificates -y
RUN apt install openssh-client -y
RUN apt install openssh-server -y
RUN apt install python3-apt -y
RUN apt install gpg -y
RUN apt install acl -y
RUN apt install apt-transport-https -y
RUN apt-get update -y
RUN apt-get install iproute2 -y
RUN apt-get install software-properties-common -y
RUN apt-add-repository 'deb http://archive.debian.org/debian-security stretch/updates main' -y
RUN apt-get update -y
RUN apt-get install openjdk-8-jdk -y
RUN systemctl disable ssh
