# syntax=docker/dockerfile:1

FROM debian:10-slim

RUN apt update
RUN apt install -y python3
RUN apt install -y python3-pip openssh-client build-essential
RUN pip3 install pip --upgrade
RUN pip3 install ansible-core>=2.11
RUN pip3 install paramiko
RUN pip3 install pytest-testinfra
RUN pip3 install pyyaml
RUN ansible-galaxy collection install community.postgresql:=1.6.0
RUN ansible-galaxy collection install ansible.posix:=1.3.0
RUN ansible-galaxy collection install community.general:=2.5.8
RUN ansible-galaxy collection install community.crypto:=1.9.12
RUN ansible-galaxy collection install community.docker:=2.7.1
RUN mkdir -p /etc/pg-ansible
COPY ./hypersql_devops-postgres* /etc/pg-ansible/
RUN cd /etc/pg-ansible; for FILE in *; do ansible-galaxy collection install $FILE --force; done