# syntax=docker/dockerfile:1

FROM registry.access.redhat.com/ubi8/ubi

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
RUN dnf install glibc-langpack-en -y
RUN dnf update -y
RUN dnf install sudo -y
RUN dnf install python3 -y
RUN dnf install ca-certificates -y
RUN dnf install openssh-clients -y
RUN dnf install openssh-server -y
RUN dnf install which -y
RUN dnf install iproute -y
