# syntax=docker/dockerfile:1

FROM debian:11-slim

ARG ansible_core_version=2.12

RUN apt update
RUN apt install -y python3
RUN apt install -y python3-pip openssh-client build-essential
RUN pip3 install pip --upgrade
RUN pip3 install ansible-core==${ansible_core_version}
RUN pip3 install paramiko
RUN pip3 install pytest-testinfra
RUN pip3 install pyyaml
RUN ansible-galaxy collection install community.postgresql:=1.6.0
RUN ansible-galaxy collection install ansible.posix:=1.3.0
RUN ansible-galaxy collection install community.general:=2.5.8
RUN ansible-galaxy collection install community.crypto:=1.9.12
