# syntax=docker/dockerfile:1

FROM oraclelinux:9

RUN dnf -y reinstall systemd
RUN (cd /etc/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
RUN yum update -y
RUN yum install iproute -y
RUN yum install sudo -y
RUN yum install python3 -y
RUN yum reinstall ca-certificates -y
RUN yum install openssh-clients -y
RUN yum install openssl -y
RUN yum install openssh-server -y
RUN yum install which -y
