# syntax=docker/dockerfile:1

FROM centos/systemd

RUN yum install iproute -y
RUN yum install sudo -y
RUN yum install python3 -y
RUN yum install ca-certificates -y
RUN yum install openssh-clients -y
RUN yum install openssh-server -y
RUN yum install which -y
