include ../../Makefile.mk

build-centos7:
	docker compose up primary1-centos7 -d

build-rocky8:
	docker compose up primary1-rocky8 -d

build-debian9:
	docker compose up primary1-debian9 -d

build-debian10:
	docker compose up primary1-debian10 -d

build-ubuntu20:
	docker compose up primary1-ubuntu20 -d
