include ../../Makefile.mk

build-centos7:
	docker compose up pem1-centos7 -d

build-rocky8:
	docker compose up pem1-rocky8 -d

build-oraclelinux7:
	docker compose up pem1-oraclelinux7 -d

build-debian10:
	docker compose up pem1-debian10 -d
