include ../../Makefile.mk

build-centos7:
	docker compose up primary1-centos7 -d
	docker compose up standby1-centos7 -d
	docker compose up standby2-centos7 -d

build-oraclelinux7:
	docker compose up primary1-oraclelinux7 -d
	docker compose up standby1-oraclelinux7 -d
	docker compose up standby2-oraclelinux7 -d
