include ../../Makefile.mk

build-rocky8:
	docker compose up primary1-rocky8 -d
	docker compose up dbt2_driver1-rocky8 -d

build-centos7:
	docker compose up primary1-centos7 -d
	docker compose up dbt2_driver1-centos7 -d