include ../../Makefile.mk

build-rocky8:
	docker compose up primary1-rocky8 -d
	docker compose up dbt2_driver1-rocky8 -d

build-almalinux8:
	docker compose up primary1-almalinux8 -d
	docker compose up dbt2_driver1-almalinux8 -d
