include ../../Makefile.mk

build-rocky8:
	docker compose up hammerdb1-rocky8 -d

build-almalinux8:
	docker compose up hammerdb1-almalinux8 -d

build-debian10:
	docker compose up hammerdb1-debian10 -d

build-ubuntu20:
	docker compose up hammerdb1-ubuntu20 -d
