include ../../Makefile.mk

build-centos7:
	docker compose up primary1-centos7 -d
	docker compose up pooler1-centos7 -d

build-rocky8:
	docker compose up primary1-rocky8 -d
	docker compose up pooler1-rocky8 -d

build-oraclelinux7:
	docker compose up primary1-oraclelinux7 -d
	docker compose up pooler1-oraclelinux7 -d

build-ubuntu20:
	docker compose up primary1-ubuntu20 -d
	docker compose up pooler1-ubuntu20 -d

build-debian10:
	docker compose up primary1-debian10 -d
	docker compose up pooler1-debian10 -d