include ../../Makefile.mk

build-centos7:
	docker compose up primary1-centos7 -d
	docker compose up pem1-centos7 -d

build-rocky8:
	docker compose up primary1-rocky8 -d
	docker compose up pem1-rocky8 -d