include ../../Makefile.mk

build-centos7:
	docker compose up primary1-centos7 -d
	docker compose up barman1-centos7 -d

build-rocky8:
	docker compose up primary1-rocky8 -d
	docker compose up barman1-rocky8 -d

build-debian10:
	docker compose up primary1-debian10 -d
	docker compose up barman1-debian10 -d

build-oraclelinux7:
	docker compose up primary1-oraclelinux7 -d
	docker compose up barman1-oraclelinux7 -d
