include ../../Makefile.mk

build-rocky8:
	docker compose up primary1-rocky8 -d
	docker compose up primary2-rocky8 -d
	docker compose up primary3-rocky8 -d

build-almalinux8:
	docker compose up primary1-almalinux8 -d
	docker compose up primary2-almalinux8 -d
	docker compose up primary3-almalinux8 -d
